name = "chickaree"
type = "webpack"
account_id = " "
zone_id = " "
route = "chickar.ee/*"

kv_namespaces = [
	 { binding = "RESOURCE_DOMAINS", preview_id = "a389c512764740e2a7bd4d857052475a", id = "39ddadfbb29c40bcb1f70ebbf6e63ec5" }
]

[site]
bucket = "./node_modules/@chickaree/web/html"
entry-point = ""
