name = "chickaree"
type = "webpack"
account_id = "75d4d63f3c7c3830efbe428bda49d72a"
zone_id = " "
route = "chickaree-web.757live.workers.dev/*"

kv_namespaces = [
	 { binding = "RESOURCE_DOMAINS", preview_id = "a389c512764740e2a7bd4d857052475a", id = "39ddadfbb29c40bcb1f70ebbf6e63ec5" }
]

[site]
bucket = "./node_modules/@chickaree/web/html"
entry-point = ""
