name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Deploy to Cloudflare
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
      - name: Purge Cloudflare Cache
        run: >-
          curl -f -X POST
          --url https://api.cloudflare.com/client/v4/zones/ed5594d679827145d1d47a063b123a22/purge_cache
          --header 'Authorization: Bearer ${{ secrets.CF_API_TOKEN }}'
          --header 'Content-Type: application/json'
          --data '{"purge_everything":true}'

